version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t devops4141/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push devops4141/todo-app:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run:
          name: Update Deployment Manifest
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/Dhanu4141/kube_manifest.git
            cd kube_manifest
            git config --global user.email "dhananjaykamble34@outlook.com"
            git config --global user.name "dhanu@dhanu"
            echo "Updating deployment manifest with build-$TAG"
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git push https://$GITHUB_PERSONAL_TOKEN@github.com/dhanu4141/kube_manifest.git HEAD:main

workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push
